### ISSUE TITLE
TouchWiz Support

### ISSUE THREAD

**Issue by ZeRoZeRoRaZ** [Magisk-Modules-Repo/EmojiOne-systemless#7]
Please add copy of NotoColorEmoji.ttf in fonts directory under name SamsungColorEmoji.ttf and it will replace ugly Samsung Emojis also on Samsung Roms.
I manualy updated your zip and it works perfectly.
[Emoji_One-v1.3-4Touchwiz.zip](https://github.com/Magisk-Modules-Repo/Magisk-EmojiOne-systemless/files/1180948/Emoji_One-v1.3-4Touchwiz.zip)

**Comment by jerbear64** [comment]
Should (finally) be good in ea09325. I don't have a Samsung device to test it on, however, but it's done identically to Blobmoji, so if that module works, this one will as well.
